Revert "drm/msm: delete msm_drm_notify.h"
This reverts commit 98ec704da565213af9a7a497f80c40eec67a2018.

../drivers/devfreq/devfreq_boost.c:11:10: fatal error: 'linux/msm_drm_notify.h' file not found

Signed-off-by: Joe7500 <joe75001@gmail.com>
Signed-off-by: alternoegraha <noegrahachan@gmail.com>
Signed-off-by: Ardia-kun <85530328+ardia-kun@users.noreply.github.com>